---
# SecretStore for infrastructure components
# Uses the same 1Password Connect as the app
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infra-onepassword
  namespace: film-review
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.film-review.svc.cluster.local:8080
      vaults:
        k8s: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
---
# PostgreSQL credentials from 1Password
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: film-review
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infra-onepassword
    kind: SecretStore
  target:
    name: basketball-film-review-postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgres-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: postgres-credentials
        property: password
    - secretKey: database
      remoteRef:
        key: postgres-credentials
        property: database
---
# MinIO credentials from 1Password
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: film-review
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infra-onepassword
    kind: SecretStore
  target:
    name: basketball-film-review-minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: minio-credentials
        property: username
    - secretKey: rootPassword
      remoteRef:
        key: minio-credentials
        property: password
