apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: basketball-film-review
  namespace: film-review
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: basketball-film-review
        namespace: flux-system
      interval: 1m
  # Automatically upgrade when new versions are available
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Values from helm/values.yaml are used by default
  # You can override them here if needed for environment-specific configs
  valuesFrom:
    - kind: ConfigMap
      name: basketball-film-review-values
      optional: true
