---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.min.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: film-review
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: ">=5.0.0"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    mode: standalone
    existingSecret: basketball-film-review-minio-credentials
    persistence:
      enabled: true
      size: 400Gi
      storageClass: "px-csi-db"
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
    service:
      type: ClusterIP
      port: 9000
    consoleService:
      enabled: true
      type: ClusterIP
      port: 9001
    buckets:
      - name: basketball-clips
        policy: none
        purge: false
