---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword
  namespace: flux-system
spec:
  interval: 1h
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: film-review
spec:
  interval: 5m
  dependsOn: []
  chart:
    spec:
      chart: connect
      version: ">=2.1.0"
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    connect:
      # Uses the pre-created op-credentials secret
      credentialsName: op-credentials
    operator:
      create: false
